# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_view.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 5, 1, 1)
        self.total_profit_percent_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.total_profit_percent_label.setFont(font)
        self.total_profit_percent_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.total_profit_percent_label.setObjectName("total_profit_percent_label")
        self.gridLayout.addWidget(self.total_profit_percent_label, 1, 0, 1, 1)
        self.total_profit_usdt_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.total_profit_usdt_label.setFont(font)
        self.total_profit_usdt_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.total_profit_usdt_label.setObjectName("total_profit_usdt_label")
        self.gridLayout.addWidget(self.total_profit_usdt_label, 1, 1, 1, 1)
        self.total_position_percent_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.total_position_percent_label.setFont(font)
        self.total_position_percent_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.total_position_percent_label.setObjectName("total_position_percent_label")
        self.gridLayout.addWidget(self.total_position_percent_label, 1, 2, 1, 1)
        self.total_position_usdt_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.total_position_usdt_label.setFont(font)
        self.total_position_usdt_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.total_position_usdt_label.setObjectName("total_position_usdt_label")
        self.gridLayout.addWidget(self.total_position_usdt_label, 1, 3, 1, 1)
        self.total_settle_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.total_settle_label.setFont(font)
        self.total_settle_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.total_settle_label.setObjectName("total_settle_label")
        self.gridLayout.addWidget(self.total_settle_label, 1, 4, 1, 1)
        self.init_balance_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.init_balance_label.setFont(font)
        self.init_balance_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.init_balance_label.setObjectName("init_balance_label")
        self.gridLayout.addWidget(self.init_balance_label, 1, 5, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout.setObjectName("formLayout")
        self.pairLabel_2 = QtWidgets.QLabel(self.groupBox_2)
        self.pairLabel_2.setObjectName("pairLabel_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pairLabel_2)
        self.pair_combobox = QtWidgets.QComboBox(self.groupBox_2)
        self.pair_combobox.setEditable(True)
        self.pair_combobox.setObjectName("pair_combobox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pair_combobox)
        self.horizontalLayout.addLayout(self.formLayout)
        self.add_button = QtWidgets.QPushButton(self.groupBox_2)
        self.add_button.setMinimumSize(QtCore.QSize(91, 0))
        self.add_button.setMaximumSize(QtCore.QSize(91, 16777215))
        self.add_button.setObjectName("add_button")
        self.horizontalLayout.addWidget(self.add_button)
        self.del_button = QtWidgets.QPushButton(self.groupBox_2)
        self.del_button.setMaximumSize(QtCore.QSize(91, 16777215))
        self.del_button.setObjectName("del_button")
        self.horizontalLayout.addWidget(self.del_button)
        self.start_button = QtWidgets.QPushButton(self.groupBox_2)
        self.start_button.setMaximumSize(QtCore.QSize(91, 16777215))
        self.start_button.setObjectName("start_button")
        self.horizontalLayout.addWidget(self.start_button)
        self.stop_button = QtWidgets.QPushButton(self.groupBox_2)
        self.stop_button.setMaximumSize(QtCore.QSize(91, 16777215))
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout.addWidget(self.stop_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 0, 5, 1, 1)
        self.coin_profit_percent_label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_profit_percent_label.setFont(font)
        self.coin_profit_percent_label.setStyleSheet("color: rgb(16, 128, 64);")
        self.coin_profit_percent_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_profit_percent_label.setObjectName("coin_profit_percent_label")
        self.gridLayout_2.addWidget(self.coin_profit_percent_label, 1, 0, 1, 1)
        self.coin_profit_usdt_label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_profit_usdt_label.setFont(font)
        self.coin_profit_usdt_label.setStyleSheet("color: rgb(16, 128, 64);")
        self.coin_profit_usdt_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_profit_usdt_label.setObjectName("coin_profit_usdt_label")
        self.gridLayout_2.addWidget(self.coin_profit_usdt_label, 1, 1, 1, 1)
        self.coin_position_amount_label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_position_amount_label.setFont(font)
        self.coin_position_amount_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_position_amount_label.setObjectName("coin_position_amount_label")
        self.gridLayout_2.addWidget(self.coin_position_amount_label, 1, 2, 1, 1)
        self.coin_position_usdt_label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_position_usdt_label.setFont(font)
        self.coin_position_usdt_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_position_usdt_label.setObjectName("coin_position_usdt_label")
        self.gridLayout_2.addWidget(self.coin_position_usdt_label, 1, 3, 1, 1)
        self.coin_avg_label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_avg_label.setFont(font)
        self.coin_avg_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_avg_label.setObjectName("coin_avg_label")
        self.gridLayout_2.addWidget(self.coin_avg_label, 1, 4, 1, 1)
        self.coin_stop_loss_label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_stop_loss_label.setFont(font)
        self.coin_stop_loss_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_stop_loss_label.setObjectName("coin_stop_loss_label")
        self.gridLayout_2.addWidget(self.coin_stop_loss_label, 1, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.coin_vol_label = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_vol_label.setFont(font)
        self.coin_vol_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_vol_label.setObjectName("coin_vol_label")
        self.gridLayout_4.addWidget(self.coin_vol_label, 3, 4, 1, 1)
        self.coin_highest_label = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_highest_label.setFont(font)
        self.coin_highest_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_highest_label.setObjectName("coin_highest_label")
        self.gridLayout_4.addWidget(self.coin_highest_label, 3, 3, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.groupBox_6)
        self.label_82.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_82.setObjectName("label_82")
        self.gridLayout_4.addWidget(self.label_82, 2, 1, 1, 1)
        self.label_85 = QtWidgets.QLabel(self.groupBox_6)
        self.label_85.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_85.setObjectName("label_85")
        self.gridLayout_4.addWidget(self.label_85, 2, 4, 1, 1)
        self.coin_open_label = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_open_label.setFont(font)
        self.coin_open_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_open_label.setObjectName("coin_open_label")
        self.gridLayout_4.addWidget(self.coin_open_label, 3, 0, 1, 1)
        self.coin_close_label = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_close_label.setFont(font)
        self.coin_close_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_close_label.setObjectName("coin_close_label")
        self.gridLayout_4.addWidget(self.coin_close_label, 3, 1, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.groupBox_6)
        self.label_84.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_84.setObjectName("label_84")
        self.gridLayout_4.addWidget(self.label_84, 2, 3, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.groupBox_6)
        self.label_83.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_83.setObjectName("label_83")
        self.gridLayout_4.addWidget(self.label_83, 2, 2, 1, 1)
        self.coin_avg_diff_usdt_label = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_avg_diff_usdt_label.setFont(font)
        self.coin_avg_diff_usdt_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_avg_diff_usdt_label.setObjectName("coin_avg_diff_usdt_label")
        self.gridLayout_4.addWidget(self.coin_avg_diff_usdt_label, 1, 2, 1, 1)
        self.coin_open_diff_percent_label = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_open_diff_percent_label.setFont(font)
        self.coin_open_diff_percent_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_open_diff_percent_label.setObjectName("coin_open_diff_percent_label")
        self.gridLayout_4.addWidget(self.coin_open_diff_percent_label, 1, 3, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.groupBox_6)
        self.label_74.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_74.setObjectName("label_74")
        self.gridLayout_4.addWidget(self.label_74, 0, 3, 1, 1)
        self.coin_open_diff_usdt_label = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_open_diff_usdt_label.setFont(font)
        self.coin_open_diff_usdt_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_open_diff_usdt_label.setObjectName("coin_open_diff_usdt_label")
        self.gridLayout_4.addWidget(self.coin_open_diff_usdt_label, 1, 4, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.groupBox_6)
        self.label_73.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_73.setObjectName("label_73")
        self.gridLayout_4.addWidget(self.label_73, 0, 2, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.groupBox_6)
        self.label_71.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_71.setObjectName("label_71")
        self.gridLayout_4.addWidget(self.label_71, 0, 0, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.groupBox_6)
        self.label_81.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_81.setObjectName("label_81")
        self.gridLayout_4.addWidget(self.label_81, 2, 0, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.groupBox_6)
        self.label_75.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_75.setObjectName("label_75")
        self.gridLayout_4.addWidget(self.label_75, 0, 4, 1, 1)
        self.coin_last_label = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_last_label.setFont(font)
        self.coin_last_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_last_label.setObjectName("coin_last_label")
        self.gridLayout_4.addWidget(self.coin_last_label, 1, 0, 1, 1)
        self.coin_avg_diff_percent_label = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_avg_diff_percent_label.setFont(font)
        self.coin_avg_diff_percent_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_avg_diff_percent_label.setObjectName("coin_avg_diff_percent_label")
        self.gridLayout_4.addWidget(self.coin_avg_diff_percent_label, 1, 1, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.groupBox_6)
        self.label_72.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_72.setObjectName("label_72")
        self.gridLayout_4.addWidget(self.label_72, 0, 1, 1, 1)
        self.coin_lowest_label = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_lowest_label.setFont(font)
        self.coin_lowest_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_lowest_label.setObjectName("coin_lowest_label")
        self.gridLayout_4.addWidget(self.coin_lowest_label, 3, 2, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_4)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.coin_buy_vol_big_label = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_buy_vol_big_label.setFont(font)
        self.coin_buy_vol_big_label.setStyleSheet("color: rgb(16, 128, 64);")
        self.coin_buy_vol_big_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_buy_vol_big_label.setObjectName("coin_buy_vol_big_label")
        self.gridLayout_3.addWidget(self.coin_buy_vol_big_label, 5, 3, 1, 1)
        self.coin_sell_vol_big_label = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_sell_vol_big_label.setFont(font)
        self.coin_sell_vol_big_label.setStyleSheet("color: rgb(252, 1, 7);")
        self.coin_sell_vol_big_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_sell_vol_big_label.setObjectName("coin_sell_vol_big_label")
        self.gridLayout_3.addWidget(self.coin_sell_vol_big_label, 5, 4, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.pairLabel_3 = QtWidgets.QLabel(self.groupBox_5)
        self.pairLabel_3.setObjectName("pairLabel_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pairLabel_3)
        self.coin_period_combobox = QtWidgets.QComboBox(self.groupBox_5)
        self.coin_period_combobox.setObjectName("coin_period_combobox")
        self.coin_period_combobox.addItem("")
        self.coin_period_combobox.addItem("")
        self.coin_period_combobox.addItem("")
        self.coin_period_combobox.addItem("")
        self.coin_period_combobox.addItem("")
        self.coin_period_combobox.addItem("")
        self.coin_period_combobox.addItem("")
        self.coin_period_combobox.addItem("")
        self.coin_period_combobox.addItem("")
        self.coin_period_combobox.addItem("")
        self.coin_period_combobox.addItem("")
        self.coin_period_combobox.addItem("")
        self.coin_period_combobox.addItem("")
        self.coin_period_combobox.addItem("")
        self.coin_period_combobox.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.coin_period_combobox)
        self.gridLayout_3.addLayout(self.formLayout_2, 0, 0, 1, 2)
        self.label_57 = QtWidgets.QLabel(self.groupBox_5)
        self.label_57.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_57.setObjectName("label_57")
        self.gridLayout_3.addWidget(self.label_57, 0, 2, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.groupBox_5)
        self.label_59.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_59.setObjectName("label_59")
        self.gridLayout_3.addWidget(self.label_59, 0, 3, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.groupBox_5)
        self.label_61.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_61.setObjectName("label_61")
        self.gridLayout_3.addWidget(self.label_61, 0, 4, 1, 1)
        self.coin_inflow_label = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_inflow_label.setFont(font)
        self.coin_inflow_label.setStyleSheet("color: rgb(16, 128, 64);")
        self.coin_inflow_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_inflow_label.setObjectName("coin_inflow_label")
        self.gridLayout_3.addWidget(self.coin_inflow_label, 1, 2, 1, 1)
        self.coin_outflow_label = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_outflow_label.setFont(font)
        self.coin_outflow_label.setStyleSheet("color: rgb(252, 1, 7);")
        self.coin_outflow_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_outflow_label.setObjectName("coin_outflow_label")
        self.gridLayout_3.addWidget(self.coin_outflow_label, 1, 3, 1, 1)
        self.coin_net_inflow_label = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_net_inflow_label.setFont(font)
        self.coin_net_inflow_label.setStyleSheet("color: rgb(16, 128, 64);")
        self.coin_net_inflow_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_net_inflow_label.setObjectName("coin_net_inflow_label")
        self.gridLayout_3.addWidget(self.coin_net_inflow_label, 1, 4, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.groupBox_5)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout_3.addWidget(self.label_42, 2, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.groupBox_5)
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_3.addWidget(self.label_43, 2, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_5)
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_3.addWidget(self.label_38, 2, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox_5)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_3.addWidget(self.label_37, 2, 3, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.groupBox_5)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_3.addWidget(self.label_41, 2, 4, 1, 1)
        self.coin_trade_count_label = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_trade_count_label.setFont(font)
        self.coin_trade_count_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_trade_count_label.setObjectName("coin_trade_count_label")
        self.gridLayout_3.addWidget(self.coin_trade_count_label, 3, 0, 1, 1)
        self.coin_buy_count_label = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_buy_count_label.setFont(font)
        self.coin_buy_count_label.setStyleSheet("color: rgb(16, 128, 64);")
        self.coin_buy_count_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_buy_count_label.setObjectName("coin_buy_count_label")
        self.gridLayout_3.addWidget(self.coin_buy_count_label, 3, 1, 1, 1)
        self.coin_sell_count_label = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_sell_count_label.setFont(font)
        self.coin_sell_count_label.setStyleSheet("color: rgb(252, 1, 7);")
        self.coin_sell_count_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_sell_count_label.setObjectName("coin_sell_count_label")
        self.gridLayout_3.addWidget(self.coin_sell_count_label, 3, 2, 1, 1)
        self.coin_buy_vol_label = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_buy_vol_label.setFont(font)
        self.coin_buy_vol_label.setStyleSheet("color: rgb(16, 128, 64);")
        self.coin_buy_vol_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_buy_vol_label.setObjectName("coin_buy_vol_label")
        self.gridLayout_3.addWidget(self.coin_buy_vol_label, 3, 3, 1, 1)
        self.coin_sell_vol_label = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_sell_vol_label.setFont(font)
        self.coin_sell_vol_label.setStyleSheet("color: rgb(252, 1, 7);")
        self.coin_sell_vol_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_sell_vol_label.setObjectName("coin_sell_vol_label")
        self.gridLayout_3.addWidget(self.coin_sell_vol_label, 3, 4, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.groupBox_5)
        self.label_52.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_52.setObjectName("label_52")
        self.gridLayout_3.addWidget(self.label_52, 4, 0, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.groupBox_5)
        self.label_53.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_53.setObjectName("label_53")
        self.gridLayout_3.addWidget(self.label_53, 4, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.groupBox_5)
        self.label_48.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_48.setObjectName("label_48")
        self.gridLayout_3.addWidget(self.label_48, 4, 2, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.groupBox_5)
        self.label_47.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_47.setObjectName("label_47")
        self.gridLayout_3.addWidget(self.label_47, 4, 3, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.groupBox_5)
        self.label_51.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_51.setObjectName("label_51")
        self.gridLayout_3.addWidget(self.label_51, 4, 4, 1, 1)
        self.coin_trade_count_big_label = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_trade_count_big_label.setFont(font)
        self.coin_trade_count_big_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_trade_count_big_label.setObjectName("coin_trade_count_big_label")
        self.gridLayout_3.addWidget(self.coin_trade_count_big_label, 5, 0, 1, 1)
        self.coin_buy_count_big_label = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_buy_count_big_label.setFont(font)
        self.coin_buy_count_big_label.setStyleSheet("color: rgb(16, 128, 64);")
        self.coin_buy_count_big_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_buy_count_big_label.setObjectName("coin_buy_count_big_label")
        self.gridLayout_3.addWidget(self.coin_buy_count_big_label, 5, 1, 1, 1)
        self.coin_sell_count_big_label = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.coin_sell_count_big_label.setFont(font)
        self.coin_sell_count_big_label.setStyleSheet("color: rgb(252, 1, 7);")
        self.coin_sell_count_big_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coin_sell_count_big_label.setObjectName("coin_sell_count_big_label")
        self.gridLayout_3.addWidget(self.coin_sell_count_big_label, 5, 2, 1, 1)
        self.coin_time_label = QtWidgets.QLabel(self.groupBox_5)
        self.coin_time_label.setObjectName("coin_time_label")
        self.gridLayout_3.addWidget(self.coin_time_label, 1, 0, 1, 2)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.log_edit = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.log_edit.setObjectName("log_edit")
        self.verticalLayout_2.addWidget(self.log_edit)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.update_deals_action = QtWidgets.QAction(MainWindow)
        self.update_deals_action.setEnabled(False)
        self.update_deals_action.setObjectName("update_deals_action")
        self.update_kline_action = QtWidgets.QAction(MainWindow)
        self.update_kline_action.setEnabled(False)
        self.update_kline_action.setObjectName("update_kline_action")
        self.update_order_action = QtWidgets.QAction(MainWindow)
        self.update_order_action.setObjectName("update_order_action")
        self.update_balance_action = QtWidgets.QAction(MainWindow)
        self.update_balance_action.setObjectName("update_balance_action")
        self.setup_action = QtWidgets.QAction(MainWindow)
        self.setup_action.setEnabled(False)
        self.setup_action.setObjectName("setup_action")
        self.clear_log_action = QtWidgets.QAction(MainWindow)
        self.clear_log_action.setObjectName("clear_log_action")
        self.toolBar.addAction(self.update_deals_action)
        self.toolBar.addAction(self.update_kline_action)
        self.toolBar.addAction(self.update_order_action)
        self.toolBar.addAction(self.update_balance_action)
        self.toolBar.addAction(self.setup_action)
        self.toolBar.addAction(self.clear_log_action)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pair_combobox, self.add_button)
        MainWindow.setTabOrder(self.add_button, self.del_button)
        MainWindow.setTabOrder(self.del_button, self.start_button)
        MainWindow.setTabOrder(self.start_button, self.stop_button)
        MainWindow.setTabOrder(self.stop_button, self.coin_period_combobox)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OKEx Dashboard"))
        self.groupBox.setTitle(_translate("MainWindow", "总览"))
        self.label_6.setText(_translate("MainWindow", "盈亏(%)"))
        self.label_5.setText(_translate("MainWindow", "盈亏"))
        self.label_2.setText(_translate("MainWindow", "仓位(%)"))
        self.label.setText(_translate("MainWindow", "仓位"))
        self.label_4.setText(_translate("MainWindow", "当前结算"))
        self.label_3.setText(_translate("MainWindow", "期初余额"))
        self.total_profit_percent_label.setText(_translate("MainWindow", "0.23"))
        self.total_profit_usdt_label.setText(_translate("MainWindow", "23425.23"))
        self.total_position_percent_label.setText(_translate("MainWindow", "12.45"))
        self.total_position_usdt_label.setText(_translate("MainWindow", "13234.23"))
        self.total_settle_label.setText(_translate("MainWindow", "23424.23"))
        self.init_balance_label.setText(_translate("MainWindow", "23123.34"))
        self.groupBox_2.setTitle(_translate("MainWindow", "分览"))
        self.pairLabel_2.setText(_translate("MainWindow", "Pair:"))
        self.add_button.setText(_translate("MainWindow", "添加"))
        self.del_button.setText(_translate("MainWindow", "删除"))
        self.start_button.setText(_translate("MainWindow", "开始"))
        self.stop_button.setText(_translate("MainWindow", "停止"))
        self.label_22.setText(_translate("MainWindow", "盈亏(%)"))
        self.label_23.setText(_translate("MainWindow", "盈亏"))
        self.label_14.setText(_translate("MainWindow", "持仓量"))
        self.label_15.setText(_translate("MainWindow", "持仓金额"))
        self.label_18.setText(_translate("MainWindow", "均价"))
        self.label_19.setText(_translate("MainWindow", "止损价"))
        self.coin_profit_percent_label.setText(_translate("MainWindow", "12.32"))
        self.coin_profit_usdt_label.setText(_translate("MainWindow", "21233.2322"))
        self.coin_position_amount_label.setText(_translate("MainWindow", "12.45"))
        self.coin_position_usdt_label.setText(_translate("MainWindow", "13234.23"))
        self.coin_avg_label.setText(_translate("MainWindow", "12.45"))
        self.coin_stop_loss_label.setText(_translate("MainWindow", "13234.23"))
        self.groupBox_6.setTitle(_translate("MainWindow", "当日数据"))
        self.coin_vol_label.setText(_translate("MainWindow", "12.45"))
        self.coin_highest_label.setText(_translate("MainWindow", "13234.23"))
        self.label_82.setText(_translate("MainWindow", "收盘价(最新价)"))
        self.label_85.setText(_translate("MainWindow", "成交量"))
        self.coin_open_label.setText(_translate("MainWindow", "1.7109"))
        self.coin_close_label.setText(_translate("MainWindow", "1.6432"))
        self.label_84.setText(_translate("MainWindow", "最高价"))
        self.label_83.setText(_translate("MainWindow", "最低价"))
        self.coin_avg_diff_usdt_label.setText(_translate("MainWindow", "123.23"))
        self.coin_open_diff_percent_label.setText(_translate("MainWindow", "23.12"))
        self.label_74.setText(_translate("MainWindow", "开盘价差(%)"))
        self.coin_open_diff_usdt_label.setText(_translate("MainWindow", "231"))
        self.label_73.setText(_translate("MainWindow", "均价价差"))
        self.label_71.setText(_translate("MainWindow", "最新价格"))
        self.label_81.setText(_translate("MainWindow", "开盘价"))
        self.label_75.setText(_translate("MainWindow", "开盘价差"))
        self.coin_last_label.setText(_translate("MainWindow", "1.9873"))
        self.coin_avg_diff_percent_label.setText(_translate("MainWindow", "2.32"))
        self.label_72.setText(_translate("MainWindow", "均价价差(%)"))
        self.coin_lowest_label.setText(_translate("MainWindow", "12.45"))
        self.groupBox_5.setTitle(_translate("MainWindow", "周期数据"))
        self.coin_buy_vol_big_label.setText(_translate("MainWindow", "13234.23"))
        self.coin_sell_vol_big_label.setText(_translate("MainWindow", "12.45"))
        self.pairLabel_3.setText(_translate("MainWindow", "统计周期："))
        self.coin_period_combobox.setItemText(0, _translate("MainWindow", "最近1分钟"))
        self.coin_period_combobox.setItemText(1, _translate("MainWindow", "最近3分钟"))
        self.coin_period_combobox.setItemText(2, _translate("MainWindow", "最近5分钟"))
        self.coin_period_combobox.setItemText(3, _translate("MainWindow", "最近15分钟"))
        self.coin_period_combobox.setItemText(4, _translate("MainWindow", "最近30分钟"))
        self.coin_period_combobox.setItemText(5, _translate("MainWindow", "最近1小时"))
        self.coin_period_combobox.setItemText(6, _translate("MainWindow", "最近2小时"))
        self.coin_period_combobox.setItemText(7, _translate("MainWindow", "最近4小时"))
        self.coin_period_combobox.setItemText(8, _translate("MainWindow", "最近6小时"))
        self.coin_period_combobox.setItemText(9, _translate("MainWindow", "最近12小时"))
        self.coin_period_combobox.setItemText(10, _translate("MainWindow", "最近1天"))
        self.coin_period_combobox.setItemText(11, _translate("MainWindow", "最近1周"))
        self.coin_period_combobox.setItemText(12, _translate("MainWindow", "今天"))
        self.coin_period_combobox.setItemText(13, _translate("MainWindow", "本周"))
        self.coin_period_combobox.setItemText(14, _translate("MainWindow", "本月"))
        self.label_57.setText(_translate("MainWindow", "流入资金"))
        self.label_59.setText(_translate("MainWindow", "流出资金"))
        self.label_61.setText(_translate("MainWindow", "净流入"))
        self.coin_inflow_label.setText(_translate("MainWindow", "2323.2323"))
        self.coin_outflow_label.setText(_translate("MainWindow", "123123.21312"))
        self.coin_net_inflow_label.setText(_translate("MainWindow", "32223.023"))
        self.label_42.setText(_translate("MainWindow", "成交笔数1"))
        self.label_43.setText(_translate("MainWindow", "买单笔数"))
        self.label_38.setText(_translate("MainWindow", "卖单笔数"))
        self.label_37.setText(_translate("MainWindow", "买单量"))
        self.label_41.setText(_translate("MainWindow", "卖单量"))
        self.coin_trade_count_label.setText(_translate("MainWindow", "23"))
        self.coin_buy_count_label.setText(_translate("MainWindow", "34"))
        self.coin_sell_count_label.setText(_translate("MainWindow", "23"))
        self.coin_buy_vol_label.setText(_translate("MainWindow", "13234.23"))
        self.coin_sell_vol_label.setText(_translate("MainWindow", "12.45"))
        self.label_52.setText(_translate("MainWindow", "大单笔数"))
        self.label_53.setText(_translate("MainWindow", "大买单笔数"))
        self.label_48.setText(_translate("MainWindow", "大卖单笔数"))
        self.label_47.setText(_translate("MainWindow", "大笔买单量"))
        self.label_51.setText(_translate("MainWindow", "大笔卖单量"))
        self.coin_trade_count_big_label.setText(_translate("MainWindow", "12"))
        self.coin_buy_count_big_label.setText(_translate("MainWindow", "23"))
        self.coin_sell_count_big_label.setText(_translate("MainWindow", "34"))
        self.coin_time_label.setText(_translate("MainWindow", "2018-04-23 23:00:00 —— 现在"))
        self.groupBox_3.setTitle(_translate("MainWindow", "日志"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.update_deals_action.setText(_translate("MainWindow", "补全交易"))
        self.update_kline_action.setText(_translate("MainWindow", "补全K线"))
        self.update_order_action.setText(_translate("MainWindow", "补全订单"))
        self.update_balance_action.setText(_translate("MainWindow", "补全余额"))
        self.setup_action.setText(_translate("MainWindow", "设置"))
        self.clear_log_action.setText(_translate("MainWindow", "清除日志"))

