# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo_depth_view_main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pair_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.pair_combobox.setEditable(True)
        self.pair_combobox.setObjectName("pair_combobox")
        self.horizontalLayout.addWidget(self.pair_combobox)
        self.add_pair_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_pair_button.setMinimumSize(QtCore.QSize(83, 0))
        self.add_pair_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.add_pair_button.setObjectName("add_pair_button")
        self.horizontalLayout.addWidget(self.add_pair_button)
        self.remove_pair_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_pair_button.setMinimumSize(QtCore.QSize(83, 0))
        self.remove_pair_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.remove_pair_button.setObjectName("remove_pair_button")
        self.horizontalLayout.addWidget(self.remove_pair_button)
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setMinimumSize(QtCore.QSize(83, 0))
        self.start_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.start_button.setObjectName("start_button")
        self.horizontalLayout.addWidget(self.start_button)
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setMinimumSize(QtCore.QSize(83, 0))
        self.stop_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout.addWidget(self.stop_button)
        self.clear_log_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_log_button.setMinimumSize(QtCore.QSize(83, 0))
        self.clear_log_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.clear_log_button.setObjectName("clear_log_button")
        self.horizontalLayout.addWidget(self.clear_log_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.asks_table = QtWidgets.QTableWidget(self.centralwidget)
        self.asks_table.setMinimumSize(QtCore.QSize(0, 0))
        self.asks_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        font.setPointSize(11)
        self.asks_table.setFont(font)
        self.asks_table.setStyleSheet("color: rgb(252, 1, 7);")
        self.asks_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.asks_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.asks_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.asks_table.setShowGrid(False)
        self.asks_table.setObjectName("asks_table")
        self.asks_table.setColumnCount(2)
        self.asks_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.asks_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.asks_table.setHorizontalHeaderItem(1, item)
        self.asks_table.horizontalHeader().setVisible(True)
        self.asks_table.verticalHeader().setVisible(False)
        self.asks_table.verticalHeader().setDefaultSectionSize(16)
        self.horizontalLayout_3.addWidget(self.asks_table)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pair_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pair_label.setFont(font)
        self.pair_label.setObjectName("pair_label")
        self.verticalLayout.addWidget(self.pair_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ticker_price_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ticker_price_label.setFont(font)
        self.ticker_price_label.setStyleSheet("color: rgb(252, 1, 7);")
        self.ticker_price_label.setObjectName("ticker_price_label")
        self.horizontalLayout_2.addWidget(self.ticker_price_label)
        self.ticker_logo_label = QtWidgets.QLabel(self.centralwidget)
        self.ticker_logo_label.setObjectName("ticker_logo_label")
        self.horizontalLayout_2.addWidget(self.ticker_logo_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.bids_table = QtWidgets.QTableWidget(self.centralwidget)
        self.bids_table.setMinimumSize(QtCore.QSize(0, 0))
        self.bids_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        font.setPointSize(11)
        self.bids_table.setFont(font)
        self.bids_table.setStyleSheet("color: rgb(16, 128, 128);")
        self.bids_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.bids_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.bids_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.bids_table.setShowGrid(False)
        self.bids_table.setObjectName("bids_table")
        self.bids_table.setColumnCount(2)
        self.bids_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.bids_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.bids_table.setHorizontalHeaderItem(1, item)
        self.bids_table.horizontalHeader().setVisible(True)
        self.bids_table.verticalHeader().setVisible(False)
        self.bids_table.verticalHeader().setDefaultSectionSize(16)
        self.horizontalLayout_3.addWidget(self.bids_table)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.log_edit = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.log_edit.setFont(font)
        self.log_edit.setReadOnly(True)
        self.log_edit.setObjectName("log_edit")
        self.verticalLayout_2.addWidget(self.log_edit)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pair_combobox, self.add_pair_button)
        MainWindow.setTabOrder(self.add_pair_button, self.remove_pair_button)
        MainWindow.setTabOrder(self.remove_pair_button, self.start_button)
        MainWindow.setTabOrder(self.start_button, self.stop_button)
        MainWindow.setTabOrder(self.stop_button, self.clear_log_button)
        MainWindow.setTabOrder(self.clear_log_button, self.asks_table)
        MainWindow.setTabOrder(self.asks_table, self.bids_table)
        MainWindow.setTabOrder(self.bids_table, self.log_edit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "demo_depth"))
        self.label.setText(_translate("MainWindow", "交易对:"))
        self.add_pair_button.setText(_translate("MainWindow", "Add"))
        self.remove_pair_button.setText(_translate("MainWindow", "Remove"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.clear_log_button.setText(_translate("MainWindow", "Clear"))
        item = self.asks_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "价格"))
        item = self.asks_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "数量"))
        self.pair_label.setText(_translate("MainWindow", "OKB_USDT"))
        self.ticker_price_label.setText(_translate("MainWindow", "1.8765"))
        self.ticker_logo_label.setText(_translate("MainWindow", "⬆︎⬇︎"))
        item = self.bids_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "价格"))
        item = self.bids_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "数量"))

