# -*- coding: utf-8 -*-
__author__ = 'Dragon Sun'


# 交易方向
TRADE_SIDE_BUY = 1
TRADE_SIDE_SELL = 2

# 订单状态
ORDER_RECALL = -1  # 撤销
ORDER_OPEN = 0  # 未成交
ORDER_PART = 1  # 部分成交
ORDER_CLOSE = 2  # 已成交
ORDER_RECALLING = 3  # 撤单中

# K线类型
KLINE_TYPE_MIN01 = 0
KLINE_TYPE_MIN03 = 1
KLINE_TYPE_MIN05 = 2
KLINE_TYPE_MIN15 = 3
KLINE_TYPE_MIN30 = 4
KLINE_TYPE_HOUR01 = 5
KLINE_TYPE_HOUR02 = 6
KLINE_TYPE_HOUR04 = 7
KLINE_TYPE_HOUR06 = 8
KLINE_TYPE_HOUR12 = 9
KLINE_TYPE_DAY = 10
KLINE_TYPE_WEEK = 11

# 时间周期
PERIOD_LAST_MIN01 = 0
PERIOD_LAST_MIN03 = 1
PERIOD_LAST_MIN05 = 2
PERIOD_LAST_MIN15 = 3
PERIOD_LAST_MIN30 = 4
PERIOD_LAST_HOUR01 = 5
PERIOD_LAST_HOUR02 = 6
PERIOD_LAST_HOUR04 = 7
PERIOD_LAST_HOUR06 = 8
PERIOD_LAST_HOUR12 = 9
PERIOD_LAST_DAY = 10
PERIOD_LAST_WEEK = 11
PERIOD_TODAY = 12
PERIOD_THIS_WEEK = 13
PERIOD_THIS_MONTH = 14
